name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -A -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} "
            cd ~/docker/projetos/make-simple-form &&
            git pull &&
            docker compose build &&
            docker compose up -d
          "
